### ISSUE TITLE
Use of `.split("/")` is (only?) blocker for Windows users

### ISSUE THREAD

**Issue by danstowell** [earthspecies/BEBE#4]
Some of the code uses `.split("/")` to split up file paths. For my students, running the code on Windows, this leads to failures when running `evaluation.py` -- it yields a KeyError because the paths do not actually get split.

The standard fix is to replace `.split(".")` with `os.path.split()`, but you could also use `os.path.basename()`.

I'm not a Windows user myself so I wouldn't be able to test a patch.

**Comment by benjaminsshoffman** [comment]
Goodness, not sure how we missed this. Thanks for opening this issue. Should be fixed now.
