### ISSUE TITLE
requirements.txt has strict requirements, unsatisfiable on current Windows/conda

### ISSUE THREAD

**Issue by danstowell** [earthspecies/BEBE#5]
When my students tried to install BEBE code on Windows, the conda install fails on this requirement:

`numba==0.34.1`

simply because this version of numba is old and no longer available from the repository. If I change the requirement from "==" to ">=" then the error goes away and pip installation completes successfully. Is it a "safe" installation? Only you can judge!

**Comment by benjaminsshoffman** [comment]
Switched requirements to non-strict. Hopefully this fixes this issue in the future.
